// // app/layout.tsx
// import type { Metadata } from "next";
// import { Roboto, Roboto_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/ui/Navbar";
// import Providers from './provider'

// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// const robotoMono = Roboto_Mono({
//   variable: "--font-roboto-mono",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${roboto.variable} ${robotoMono.variable}`}>
//         <Providers>
//           <Navbar />
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }



// // app/layout.tsx
// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import { Providers } from './providers';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import './globals.css';
// import dynamic from 'next/dynamic';
// import Navbar from "@/components/layout/Navbar";


// const BootstrapClient = dynamic(
//   () => import('../components/BootstrapClient'),
//   { ssr: false }
// );

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'MatrimonyMatch',
//   description: 'Find your perfect partner',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Providers>
//           {children}
//           <BootstrapClient />
//         </Providers>
//       </body>
//     </html>
//   );
// }


// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from "@/components/layout/Navbar";
import BootstrapClient from "@/components/BootstrapClient"; // Direct import
import BootstrapLoader from "@/components/BootstrapLoader";
import 'bootstrap/dist/css/bootstrap.min.css';
import Providers from './provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Matrimony App',
  description: 'Find your perfect match',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // return (
  //   <html lang="en">
  //     <body className={inter.className}>
  //       <Providers />
  //       <Navbar />
  //       {children}
  //       <BootstrapClient />
  //       <BootstrapLoader />
  //       </Providers>

        
  //     </body>
  //   </html>
  // );
 return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <BootstrapClient />
        </Providers>
      </body>
    </html>
  );

}